#!/usr/bin/env bash
#Creates the file /var/run/holbertonscript.pid containing its PID
touch /var/run/holbertonscript.pid
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
